package View;
// Generated 14/05/2018 02:53:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank"
    ,catalog="db_match"
)
public class Bank  implements java.io.Serializable {


     private Integer idbank;
     private String name;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Bank() {
    }

    public Bank(String name, Set<Payment> payments) {
       this.name = name;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbank", unique=true, nullable=false)
    public Integer getIdbank() {
        return this.idbank;
    }
    
    public void setIdbank(Integer idbank) {
        this.idbank = idbank;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bank")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


