package View;
// Generated 14/05/2018 02:53:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="db_match"
)
public class Payment  implements java.io.Serializable {


     private String idpayment;
     private Bank bank;
     private Ticket ticket;

    public Payment() {
    }

    public Payment(String idpayment, Bank bank, Ticket ticket) {
       this.idpayment = idpayment;
       this.bank = bank;
       this.ticket = ticket;
    }
   
     @Id 

    
    @Column(name="idpayment", unique=true, nullable=false, length=25)
    public String getIdpayment() {
        return this.idpayment;
    }
    
    public void setIdpayment(String idpayment) {
        this.idpayment = idpayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bank_idbank", nullable=false)
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ticket_idticket", nullable=false)
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }




}


