package View;
// Generated 14/05/2018 02:53:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
    ,catalog="db_match"
)
public class Ticket  implements java.io.Serializable {


     private Integer idticket;
     private Match match;
     private Date date;
     private String dni;
     private String zone;
     private Float price;
     private String correlative;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Ticket() {
    }

	
    public Ticket(Match match, String correlative) {
        this.match = match;
        this.correlative = correlative;
    }
    public Ticket(Match match, Date date, String dni, String zone, Float price, String correlative, Set<Payment> payments) {
       this.match = match;
       this.date = date;
       this.dni = dni;
       this.zone = zone;
       this.price = price;
       this.correlative = correlative;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idticket", unique=true, nullable=false)
    public Integer getIdticket() {
        return this.idticket;
    }
    
    public void setIdticket(Integer idticket) {
        this.idticket = idticket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="match_idmatch", nullable=false)
    public Match getMatch() {
        return this.match;
    }
    
    public void setMatch(Match match) {
        this.match = match;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="dni", length=45)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="zone", length=45)
    public String getZone() {
        return this.zone;
    }
    
    public void setZone(String zone) {
        this.zone = zone;
    }

    
    @Column(name="price", precision=6)
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }

    
    @Column(name="correlative", nullable=false, length=40)
    public String getCorrelative() {
        return this.correlative;
    }
    
    public void setCorrelative(String correlative) {
        this.correlative = correlative;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


